FROM python:3.7

WORKDIR /home
RUN mkdir data
RUN mkdir tensorboard
RUN mkdir storage
RUN mkdir src
WORKDIR /home/src
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
WORKDIR /home/src/scripts
